spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/aquarium
    username: cat
    password: 123

  jpa:
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl